# Generated by Django 4.2.3 on 2023-09-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_recipereview_delete_recipesrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereview',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
    ]
