# Generated by Django 4.2.3 on 2023-09-16 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.TextField(default='path/to/placeholder'),
        ),
    ]
