# Generated by Django 4.2.3 on 2023-09-16 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/food-project-8d454.appspot.com/o/profile_images%2Fplaceholder.jpeg?alt=media&token=88e7e170-20a7-4ff8-af75-7e49381cc3f6'),
        )
    ]
