# Generated by Django 4.2.3 on 2023-09-18 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_cuisines_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisines',
            name='country',
            field=models.CharField(default=models.CharField(max_length=30, primary_key=True, serialize=False), max_length=64),
        )
    ]
