# Generated by Django 4.2.3 on 2023-09-18 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_cuisines_country_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines',
            name='country',
            field=models.CharField(default=django.db.models.fields.Field.get_attname, max_length=64),
        ),
        migrations.AlterField(
            model_name='cuisines',
            name='cuisine',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
