# Generated by Django 4.2.3 on 2023-09-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredient_api_id_recipe_uuid_alter_cuisines_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines',
            name='country',
            field=models.CharField(default='other', max_length=64),
        ),
    ]
