# Generated by Django 4.2.3 on 2023-09-24 11:09

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeslikes',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='recipeslikes',
            unique_together={('user', 'recipe')},
        ),
    ]
