# Generated by Django 4.2.3 on 2023-09-25 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipesLikes',
        ),
    ]
