# Generated by Django 4.2.3 on 2023-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredient_api_id_recipe_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='Not specified', max_length=50),
        )
    ]
